---
name: "🚀 GitHub Pages"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["lib/**"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
      - name: ⏫ Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './lib'
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: lib
          user_name: digital-teams[bot]
          user_email: digital-teams@pm.me
