---
name: "🚀 GitHub Pages"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["lib/**"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: lib
          user_name: digital-teams[bot]
          user_email: digital-teams@pm.me
