---
name: "⭕ Trunk"
on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch: {}

jobs:
  check:
    name: "⚡"
    uses: z-shell/.github/.github/workflows/trunk.yml@main
    with:
      arguments: "--no-progress"
      get_dependencies: "sudo apt update && sudo apt-get install -yq zsh"
