---
name: "🤠 Wrangler"

on:
  schedule:
    - cron: "0 03 * * 1/3"
  push:
    branches: [main]
    paths:
      - "lib/**"
      - "workers/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose an environment to deploy to: <dev|staging|prod>"
        required: true
        default: "dev"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: wrangler
    steps:
      - uses: actions/checkout@v3
      - name: "🤠 Deploy > get"
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "workers/get"
          command: "publish"
      - name: "🤠 Deploy > init"
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "workers/init"
          command: "publish"
      - name: "🤠 Deploy > raw"
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "workers/raw"
          command: "publish"
      - name: "🤠 Deploy > cdn"
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "workers/cdn"
          command: "publish"
      - name: "🤠 Deploy > r2-store"
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "workers/r2-store"
          command: "publish"
